### ISSUE TITLE
No Timepicker or Timepicker description on service alerts

### ISSUE THREAD

**Issue by glassdimly** [glassdimly/amtrack_downeaster#1]
Implement Timepicker for usability: http://jonthornton.github.io/jquery-timepicker/

See: http://de.jeremy/admin/structure/taxonomy/manage/schedule_exceptions/add

**Comment by glassdimly** [comment]
See: https://www.drupal.org/node/1838234

**Comment by dougmorin** [comment]
Let's just go with the default date/time field for the time being.
