### ISSUE TITLE
Which fields are required?

### ISSUE THREAD

**Issue by glassdimly** [glassdimly/amtrack_downeaster#10]
I have made some assumptions about what fields are required, generally erring on the side of not-required.

Here is my list of content types (rather than paging through the google doc).

Would you like to add  bold **(R)** to any fields that are required?

Or, you can simply trust my judgement.

Announcement 
	•	Title
	⁃	Text	
	•	Announcement Description
	⁃	HTML	
	•	Image		
	⁃	Image Uploader
	•	URL
	⁃	Link	
	•	Related Station
	⁃	Content Type Selector (Multi, Stations Content Type) 	

2-3
		
Service Alert 
	•	Title
	⁃	Text
	•	Service Alert Description
	⁃	HTML
	•	Date and Time Range (Start Date and End Date)
	⁃	Date and Time
	•	Incident Type	
	⁃	Taxonomy Selector (Incident Type Taxonomy)

Deals
	•	TItle
	⁃	Text
	•	Description
	⁃	HTML
	•	Actual Discount
	⁃	Text
	•	Code
	⁃	Text
	•	Tickets purchased 3 days in advance
	⁃	Checkbox
	•	Can be discounted online
	⁃	Checkbox
	•	Restrictions
	⁃	HTML
	•	I.D. Type
	⁃	Taxonomy Selector (Multi, I.D. Type Taxonomy)
	•	More Info URL
	⁃	URL
	•	End Date
	⁃	Date
	•	Image
	⁃	Image

Highlight
	•	Highlight Title (Title)	
	⁃	Text
	•	Highlight Description
	⁃	HTML
	•	Image	
	⁃	Image
	•	URL
	⁃	URL
	•	Icon
	⁃	Taxonomy Selector (Icon Taxonomy)

Station
	•	Order
	⁃	Weight (Draggable) What does this mean?
	•	Station Name (Title)	
	⁃	Text
	•	Station Code	
	⁃	Text
	•	State	
	⁃	Taxonomy Selector (State Connections Taxonomy)
	•	Station Description	
	⁃	HTML
	•	Subtitle
	⁃	Text
	•	Station Facility Name
	⁃	Text
	•	Address	
	⁃	Address
	•	Parking
	⁃	HTML
	•	Ticket Agent Hours
	⁃	HTML
	•	Quik-Trak Ticketing Hours
	⁃	HTML
	•	To Trip Note
	⁃	HTML
	•	Paragraphs
	⁃	Connection  Need to understand this.
	⁃	Description (for all connections)
	⁃	HTML
	⁃	Connections (Multi field)		
	⁃	Taxonomy Selector (Icon Taxonomy)
	⁃	HTML
	•	Station Images (Multi Field)
	⁃	Image
	•	Connection Graphic	
	⁃	Image

FAQs
	•	Question (Title)
	⁃	Text
	•	Answer
	⁃	HTML
	•	Category			
	⁃	Taxonomy Selector (FAQs Category Taxonomy)

Sports Packages
	•	Package Title (Title)
	⁃	Text, i.e. Boston, MA
	•	Package Description
	⁃	HTML	
	•	URL
	⁃	URL
	•	Image	
	⁃	Image	
	•	Icon
	⁃	Taxonomy Selector (Icon Taxonomy)	

Downeaster Packages
	•	Package Title (Title)
	⁃	Text, i.e. Boston, MA
	•	Package Description
	⁃	HTML	
	•	URL
	⁃	URL
	•	Image	
	⁃	Image	
	•	Station
	⁃	Taxonomy Selector

Normal taxonomies (no special fields)
	•	Exceptions Type
	•	State Connections
	•	I.D. Type
	•	FAQ Categories

Normal taxonomies w/ description
	•	Stop Type

Special taxonomies:

Trains
	•	Train Number
	⁃	Text	
	•	Direction
	⁃	Select List (i.e. Southbound,Northbound)

Incident Types
	•	Incident
	⁃	Text
	•	Icon
	⁃	Taxonomy Selector (Icon Taxonomy) Is this a taxonomy referencing another taxonomy? Why is this a taxonomy then? What’s used to differentiate?
	•	Color:  Is this a hex value? Colorpicker. Fine
	⁃	Text

Fares
	•	From Station
	⁃	Content Type Selector (Station Content Type)
	•	To Station
	⁃	Content Type Selector (Station Content Type)
	•	Fare
	⁃	Currency or Number (rounded to Whole Number)

Connections
	•	Connections
	⁃	Name
	•	Icon
	⁃	Taxonomy Selector (Icon Taxonomy)

Amenities
	•	Amenity
	⁃	Text
	•	Icon
	⁃	Taxonomy Selector (Icon Taxonomy)
	•	More Info URL
	⁃	Node Search/URL

Icons
	•	Name
	⁃	Text
	•	Icon
	⁃	Image

**Comment by dougmorin** [comment]
Yeah, I would say that the required/not required status is NOT as big of a deal right now?  Typically i'll roll out the CT's with no requirement (except for the obvious ones) then when building out if i find that I need a value to be there i'll check it as required.  Thankfully, these fields are easy to change in the future with it comes to the required/not required status.
