### ISSUE TITLE
Train Direction: Single or Multiple?

### ISSUE THREAD

**Issue by glassdimly** [glassdimly/amtrack_downeaster#5]
Currently, trains have to choose: northbound or southbound.

However... this doesn't make sense to me. It would seem to me that all trains are both north and south bound, as they all must go down the line and back up. Should I change this to multiple value select or remove entirely?

http://de.jeremy/admin/structure/taxonomy/manage/trains/overview/fields/taxonomy_term.trains.field_train_direction

**Comment by dougmorin** [comment]
The same train running south will have a completely different number when it returns north.  This is for consistency for the person who goes to commute every morning, they will ALWAYS get on the same train number heading north regardless of which physical train they get on.
