### ISSUE TITLE
Colorpicker UI

### ISSUE THREAD

**Issue by glassdimly** [glassdimly/amtrack_downeaster#6]
Help text not appearing on color field. 

Colorpicker not installed/working for hex field.

http://de.jeremy/admin/structure/taxonomy/manage/incident_types/add

**Comment by glassdimly** [comment]
See bug: https://www.drupal.org/node/2885071#comment-12122672

**Comment by dougmorin** [comment]
If we can't proceed with the color picker I would just use a text field for them to apply the hex.  We can apply it later if it becomes required of us.
