### ISSUE TITLE
Amenities: URL or node reference?

### ISSUE THREAD

**Issue by glassdimly** [glassdimly/amtrack_downeaster#9]
I see on the Amenities taxonomy type that there is a field "More Info URL: Node Search / URL"

I have implemented this as a simply URL field, without a title. I.e., there would be fixed text "More Info" and the URL I've added would allow users to create a link.

You have indicated "Node search." Should this field instead by a node reference? Or should it remain as a URL?

**Comment by dougmorin** [comment]
I think if we do URL, we can specify if it can search for a node and use that URL or if it's just an external URL.

**Comment by glassdimly** [comment]
Hey Doug,

Looks like this would need to be custom. There is a [D7 module](https://www.drupal.org/project/nodereference_url), but no D8 module (want to find me one?).

I could do some sort of conditional field (checkbox) which shows or hides either a URL or a nodereference field. That's three fields, and two field displays later. Adds some hours down the line.

Not a problem to do, I'm just leaving it up to you to decide if you want that.

**Comment by dougmorin** [comment]
Just use a URL field.

**Comment by glassdimly** [comment]
@dougmorin Turns out I'm totally wrong on this. Drupal 8 has implemented URL fields as node references or links.

Apologies, my D8 work to date has been at the module and theme layers, working with site builders. 

Closing, implemented as originally requested.
